// Data extracted from Protonmatter/cosmos — solar-system.dc.html, the-moons.dc.html,
// junocam-explorer.dc.html. Figures: NASA Planetary Fact Sheets · IAU WGCCRE 2015.
export const BODIES = [
  { id:'sun', name:'The Sun', kicker:'The star', hook:'A G2V star holding 99.86% of the system\u2019s mass.', img:'planets/sun.png', square:true,
    alt:'The Sun as a full orange disc, mottled with active regions and a flare at the limb', credit:'Full disc in extreme ultraviolet. NASA/SDO.',
    desc:'A G2V main-sequence star; luminosity 3.828\u00d710\u00b2\u2076 W. Rotates differentially (~25 d equator, ~34 d poles). Surface granulation, sunspots, an X-ray corona at ~1\u20133 MK, and a continuous solar wind.',
    g:274.0, au:0,
    facts:[['Radius','695,700 km'],['Mass','1.9885\u00d710\u00b3\u2070 kg \u2014 332,950 Earths'],['Surface gravity','274.0 m/s\u00b2'],['Rotation','25.38 d (Carrington sidereal)'],['Axial tilt','7.25\u00b0'],['Effective temperature','5,772 K \u2014 5,499 \u00b0C'],['Composition','H\u2082 plasma \u2014 73% H, 25% He by mass'],['Escape velocity','617.5 km/s']] },
  { id:'mercury', name:'Mercury', kicker:'First planet from the Sun', hook:'Airless, cratered, locked in a 3:2 waltz with the Sun.', img:'planets/mercury.png', square:true,
    alt:'Mercury as a full grey disc, densely cratered from pole to pole', credit:'Global mosaic. NASA/Johns Hopkins APL/Carnegie Institution.',
    desc:'Airless, heavily cratered, 3:2 spin\u2013orbit resonance. A weak global dipole \u2014 surface field ~1% of Earth\u2019s, dipole moment ~0.06% \u2014 sustains a small magnetosphere.',
    g:3.70, au:0.39,
    facts:[['Equatorial radius','2,439.7 km'],['Mass','3.301\u00d710\u00b2\u00b3 kg \u2014 0.055 Earths'],['Surface gravity','3.70 m/s\u00b2'],['Rotation','58.65 d \u2014 3:2 with its year'],['Axial tilt','0.034\u00b0'],['Mean temperature','440 K \u2014 167 \u00b0C'],['Atmosphere','Trace exosphere \u2014 O, Na, H, He, K'],['Magnetic field','0.0006\u00d7 Earth\u2019s dipole']] },
  { id:'venus', name:'Venus', kicker:'Second planet from the Sun', hook:'A day longer than its year \u2014 turning backwards.', img:'planets/venus.png', square:true,
    alt:'Venus as a full ochre disc, its surface picked out in radar', credit:'Radar surface, colourised. NASA/JPL-Caltech.',
    desc:'A runaway greenhouse: 92 bar of CO\u2082, 737 K surface. Rotates retrograde once per 243 days \u2014 slower than its year. No intrinsic magnetic field (only an induced one).',
    g:8.87, au:0.72,
    facts:[['Equatorial radius','6,051.8 km'],['Mass','4.867\u00d710\u00b2\u2074 kg \u2014 0.815 Earths'],['Surface gravity','8.87 m/s\u00b2'],['Rotation','243.02 d, retrograde'],['Axial tilt','177.36\u00b0 \u2014 effectively upside down'],['Mean temperature','737 K \u2014 464 \u00b0C'],['Atmosphere','92 bar \u2014 96.5% CO\u2082, 3.5% N\u2082'],['Magnetic field','None intrinsic \u2014 induced only']] },
  { id:'earth', name:'Earth', kicker:'Third planet from the Sun', hook:'The reference body. Everything else is quoted against it.', img:'planets/earth.png',
    alt:'Earth as a full disc: Africa, Europe and the Indian Ocean under scattered cloud', credit:'Full disc, sunlit face. NASA.',
    desc:'Liquid-water oceans, a nitrogen\u2013oxygen atmosphere, and a strong dipole field (the reference, 8\u00d710\u00b2\u00b2 A\u00b7m\u00b2) driving a protective magnetosphere and aurorae.',
    g:9.80, au:1, moons:'earth',
    facts:[['Equatorial radius','6,378.1 km \u2014 polar 6,356.8'],['Mass','5.9722\u00d710\u00b2\u2074 kg \u2014 the reference'],['Surface gravity','9.80 m/s\u00b2'],['Rotation','23.9345 h (sidereal)'],['Axial tilt','23.44\u00b0 \u2014 precessing over ~25,770 y'],['Mean temperature','288 K \u2014 15 \u00b0C'],['Atmosphere','1.0 bar \u2014 78% N\u2082, 21% O\u2082, 1% Ar'],['Magnetic field','8\u00d710\u00b2\u00b2 A\u00b7m\u00b2 \u2014 the reference dipole']] },
  { id:'mars', name:'Mars', kicker:'Fourth planet from the Sun', hook:'Thin air, ice caps, iron-oxide dust \u2014 and two small moons.', img:'moons/mars-moons.png',
    alt:'Mars with Phobos and Deimos alongside, shown at their relative sizes', credit:'Mars with both moons at their relative sizes. NASA/JPL-Caltech/Malin Space Science Systems.',
    desc:'Thin CO\u2082 air, polar CO\u2082/water ice caps, iron-oxide dust. No global field today \u2014 only crustal remanent magnetism in the southern highlands.',
    g:3.71, au:1.52, moons:'mars',
    facts:[['Equatorial radius','3,396.2 km \u2014 polar 3,376.2'],['Mass','6.417\u00d710\u00b2\u00b3 kg \u2014 0.107 Earths'],['Surface gravity','3.71 m/s\u00b2'],['Rotation','24.6229 h'],['Axial tilt','25.19\u00b0'],['Mean temperature','210 K \u2014 \u221263 \u00b0C'],['Atmosphere','0.0064 bar \u2014 95% CO\u2082, 2.7% N\u2082'],['Magnetic field','None global \u2014 crustal remanence']] },
  { id:'jupiter', name:'Jupiter', kicker:'Fifth planet from the Sun', hook:'The largest planet, and the fastest day \u2014 9.9 hours.', img:'images/27-full-disc.png', square:true,
    alt:'Jupiter as a full banded disc, its southern hemisphere mottled with storms', credit:'JunoCam full disc. NASA/JPL-Caltech/SwRI/MSSS, processed by a citizen scientist.',
    desc:'The largest planet \u2014 visibly oblate (flattening 6.5%). Fastest rotation (9.9 h) drives zonal bands and the centuries-old Great Red Spot. A colossal magnetosphere ~20,000\u00d7 Earth\u2019s dipole.',
    g:24.79, au:5.2, moons:'jupiter', gallery:true,
    facts:[['Equatorial radius','71,492 km \u2014 polar 66,854'],['Mass','1.898\u00d710\u00b2\u2077 kg \u2014 318 Earths'],['Surface gravity','24.79 m/s\u00b2'],['Rotation','9.9259 h \u2014 the fastest'],['Axial tilt','3.13\u00b0'],['Mean temperature','165 K \u2014 \u2212108 \u00b0C'],['Atmosphere','90% H\u2082, 10% He; NH\u2083/H\u2082O clouds'],['Magnetic field','20,000\u00d7 Earth\u2019s dipole']] },
  { id:'saturn', name:'Saturn', kicker:'Sixth planet from the Sun', hook:'Less dense than water. It would float.', img:'planets/saturn.png',
    alt:'Saturn from above, its rings casting a hard shadow across the northern hemisphere', credit:'Cassini mosaic, 2016. NASA/JPL-Caltech/Space Science Institute.',
    desc:'Less dense than water. Rings of ice and rock from 1.2 to 2.3 Saturn-radii, split by the Cassini Division. The most oblate planet, flattened 9.8%.',
    g:10.44, au:9.5, moons:'saturn',
    facts:[['Equatorial radius','60,268 km \u2014 polar 54,364'],['Mass','5.683\u00d710\u00b2\u2076 kg \u2014 95 Earths'],['Density','0.687 g/cm\u00b3 \u2014 it would float'],['Rotation','10.656 h'],['Axial tilt','26.73\u00b0'],['Rings','74,500 \u2013 136,780 km from centre'],['Mean temperature','134 K \u2014 \u2212139 \u00b0C'],['Magnetic field','580\u00d7 Earth\u2019s dipole']] },
  { id:'uranus', name:'Uranus', kicker:'Seventh planet from the Sun', hook:'Tipped 98\u00b0 \u2014 it rolls along its orbit.', img:'planets/uranus.png',
    alt:'Uranus as a featureless pale blue-green disc', credit:'Voyager 2, 1986. NASA/JPL-Caltech.',
    desc:'Tipped 98\u00b0 \u2014 it rolls along its orbit on its side. Methane absorbs red light, giving its cyan hue. A field tilted 59\u00b0 from the spin axis and offset from centre.',
    g:8.69, au:19.2, moons:'uranus',
    facts:[['Equatorial radius','25,559 km \u2014 polar 24,973'],['Mass','8.681\u00d710\u00b2\u2075 kg \u2014 14.5 Earths'],['Surface gravity','8.69 m/s\u00b2'],['Rotation','17.24 h, retrograde'],['Axial tilt','97.77\u00b0 \u2014 on its side'],['Mean temperature','76 K \u2014 \u2212197 \u00b0C'],['Atmosphere','83% H\u2082, 15% He, 2% CH\u2084'],['Magnetic field','50\u00d7 Earth\u2019s, tilted 59\u00b0']] },
  { id:'neptune', name:'Neptune', kicker:'Eighth planet from the Sun', hook:'The strongest winds in the solar system \u2014 2,000 km/h.', img:'planets/neptune.png',
    alt:'Neptune as a deep blue disc with the Great Dark Spot near the centre', credit:'Voyager 2, 1989. NASA/JPL-Caltech.',
    desc:'Deepest blue of the giants, with the strongest winds in the solar system (~2,000 km/h) and transient dark storms. A field tilted 47\u00b0 and offset.',
    g:11.15, au:30.1, moons:'neptune',
    facts:[['Equatorial radius','24,764 km \u2014 polar 24,341'],['Mass','1.024\u00d710\u00b2\u2076 kg \u2014 17.1 Earths'],['Surface gravity','11.15 m/s\u00b2'],['Rotation','15.9663 h (IAU 2015)'],['Axial tilt','28.32\u00b0'],['Mean temperature','72 K \u2014 \u2212201 \u00b0C'],['Atmosphere','80% H\u2082, 19% He, 1.5% CH\u2084'],['Magnetic field','27\u00d7 Earth\u2019s, tilted 47\u00b0']] }
];

export const SYSTEMS = [
  { id:'earth', name:'Earth', count:1 }, { id:'mars', name:'Mars', count:2 },
  { id:'jupiter', name:'Jupiter', count:4 }, { id:'saturn', name:'Saturn', count:7 },
  { id:'uranus', name:'Uranus', count:5 }, { id:'neptune', name:'Neptune', count:3 }
];

export const MOONS = [
  { id:'moon', name:'The Moon', system:'earth', roman:'Earth\u2019s satellite', disc:'moons/moon.png', r:1737.4, period:27.322,
    blurb:'Tidally locked, no air and no field. Libration shows us 59% of it.',
    photo:'moons/moon.png', credit:'NASA.',
    desc:'Earth\u2019s tidally-locked companion: dark basaltic maria, bright cratered highlands, no atmosphere or global field. Libration \u2014 7.9\u00b0 in longitude, 6.7\u00b0 in latitude \u2014 exposes 59% of the surface over time.',
    facts:[['Radius','1,737.4 km'],['Mass','7.346\u00d710\u00b2\u00b2 kg \u2014 0.0123 Earths'],['Surface gravity','1.62 m/s\u00b2'],['Rotation','27.322 d \u2014 synchronous'],['Mean temperature','250 K \u2014 \u221223 \u00b0C']] },
  { id:'phobos', name:'Phobos', system:'mars', roman:'Mars I', disc:'moons/phobos.png', r:11.1, period:0.319,
    blurb:'Rises in the west, twice a day \u2014 and it is falling.',
    photo:'moons/phobos.png', credit:'NASA/JPL-Caltech/University of Arizona.',
    desc:'Eleven kilometres across, orbiting in under eight hours \u2014 faster than Mars turns, so from the surface it rises in the west and sets in the east twice a day. Tidal drag is pulling it inward; in tens of millions of years it will break apart into a ring.',
    facts:[['Radius','11.1 km'],['Orbit','9,379 km, 0.319 d'],['Density','1.872 g/cm\u00b3']] },
  { id:'deimos', name:'Deimos', system:'mars', roman:'Mars II', disc:'moons/deimos.png', r:6.2, period:1.262,
    blurb:'A smooth pale wedge, barely more than gravel.',
    photo:'moons/deimos.png', credit:'NASA/JPL-Caltech/MSSS.',
    desc:'Too small for gravity to pull it into a sphere \u2014 a smooth pale wedge with a few shallow craters, probably a captured asteroid like its sibling.',
    facts:[['Radius','6.2 km'],['Orbit','23,459 km, 1.262 d'],['Density','1.471 g/cm\u00b3']] },
  { id:'io', name:'Io', system:'jupiter', roman:'Jupiter I', disc:'moons/gp-io.png', r:1821.5, period:1.769,
    blurb:'The most volcanically active world in the solar system.',
    photo:'moons/io-plume.png', credit:'A plume standing 140 km above the limb, seen by Galileo. NASA/JPL/University of Arizona.',
    desc:'The most volcanically active world in the solar system \u2014 sulfur frosts, 400+ volcanoes. Squeezed by Jupiter and pulled on by Europa and Ganymede, its interior is kneaded hard enough to stay molten. The material it throws off feeds the plasma torus that powers Jupiter\u2019s radiation belts \u2014 the same belts steadily wrecking JunoCam.',
    facts:[['Radius','1,821.5 km'],['Orbit','422,019 km, 1.769 d'],['Density','3.528 g/cm\u00b3 \u2014 the densest moon'],['Eccentricity','0.0036 \u2014 small, and enough']] },
  { id:'europa', name:'Europa', system:'jupiter', roman:'Jupiter II', disc:'moons/gp-europa.png', r:1560.8, period:3.551,
    blurb:'A cracked ice shell over a global salt-water ocean.',
    photo:'moons/europa.png', credit:'Galileo imagery, reprocessed in 2014 to approximate natural colour. NASA/JPL-Caltech/SETI Institute.',
    desc:'The smoothest body in the solar system: an ice shell over a global salt-water ocean holding roughly twice the water of every ocean on Earth. The rust-coloured streaks are salts and sulfur compounds carried up through the cracks \u2014 the ocean, sampled at the surface.',
    facts:[['Radius','1,560.8 km'],['Orbit','671,100 km, 3.551 d'],['Density','3.013 g/cm\u00b3']] },
  { id:'ganymede', name:'Ganymede', system:'jupiter', roman:'Jupiter III', disc:'moons/gp-ganymede.png', r:2631.2, period:7.155,
    blurb:'Largest moon in the solar system \u2014 bigger than Mercury.',
    photo:'moons/ganymede.png', credit:'Juno, 2021. NASA/JPL-Caltech/SwRI/MSSS.',
    desc:'Larger than Mercury, and the only moon known to generate its own magnetic field. Bright young craters cut across darker terrain four billion years old.',
    facts:[['Radius','2,631.2 km'],['Orbit period','7.155 d'],['Density','1.94 g/cm\u00b3 \u2014 roughly half water ice']] },
  { id:'callisto', name:'Callisto', system:'jupiter', roman:'Jupiter IV', disc:'moons/disc-callisto.png', r:2410.3, period:16.689,
    blurb:'The most heavily cratered object known.',
    photo:'moons/callisto.png', credit:'Galileo, 2001. NASA/JPL/DLR.',
    desc:'The most heavily cratered object known. Nothing has resurfaced it since the early solar system, so every impact it has ever taken is still there to count \u2014 geologically dead for ~4 billion years.',
    facts:[['Radius','2,410.3 km'],['Orbit period','16.689 d'],['Density','1.83 g/cm\u00b3']] },
  { id:'mimas', name:'Mimas', system:'saturn', roman:'Saturn I', disc:'moons/mimas.png', discPos:'62% 50%', r:198.2, period:0.942,
    blurb:'Herschel crater spans a third of its diameter.',
    photo:'moons/mimas.png', credit:'Herschel crater at the terminator. NASA/JPL-Caltech/Space Science Institute.',
    desc:'Herschel crater spans a third of its diameter \u2014 whatever struck Mimas came close to destroying it. At 198 kilometres it is the smallest of Saturn\u2019s round moons, and only just round: its own gravity barely wins.',
    facts:[['Radius','198.2 km'],['Orbit','186,007 km, 0.942 d'],['Density','1.150 g/cm\u00b3 \u2014 nearly all ice']] },
  { id:'enceladus', name:'Enceladus', system:'saturn', roman:'Saturn II', disc:'moons/enceladus-ice.png', discPos:'center 42%', r:252.1, period:1.370,
    blurb:'Brightest surface in the solar system, venting water ice.',
    photo:'moons/enceladus-geysers.png', credit:'Jets rising from the fractures near the south pole, backlit by the Sun. NASA/JPL-Caltech/Space Science Institute.',
    desc:'Brightest surface in the solar system, venting water ice from a subsurface ocean. Two hundred and fifty kilometres across \u2014 small enough to sit inside the length of Britain \u2014 and geologically alive.',
    facts:[['Radius','252.1 km'],['Orbit period','1.370 d'],['Surface','Fractured water ice, geysers at the south pole']] },
  { id:'tethys', name:'Tethys', system:'saturn', roman:'Saturn III', disc:'moons/tethys.png', r:531.1, period:1.888,
    blurb:'Almost pure water ice, scarred by the vast Ithaca Chasma.',
    photo:'moons/tethys.png', credit:'NASA/JPL-Caltech/Space Science Institute.',
    desc:'Almost pure water ice \u2014 at 0.98 g/cm\u00b3 it is barely denser than the stuff it is made of \u2014 scarred by the vast Ithaca Chasma.',
    facts:[['Radius','531.1 km'],['Orbit period','1.888 d'],['Density','0.98 g/cm\u00b3']] },
  { id:'dione', name:'Dione', system:'saturn', roman:'Saturn IV', disc:'moons/dione.png', r:561.4, period:2.737,
    blurb:'Wispy ice cliffs streak its trailing hemisphere.',
    photo:'moons/dione.png', credit:'NASA/JPL-Caltech/Space Science Institute.',
    desc:'Bright cratered ice streaked with wispy cliffs across its trailing hemisphere.',
    facts:[['Radius','561.4 km'],['Orbit period','2.737 d']] },
  { id:'rhea', name:'Rhea', system:'saturn', roman:'Saturn V', disc:'moons/rhea.png', r:763.5, period:4.518,
    blurb:'Saturn\u2019s second largest \u2014 an ancient, cratered iceball.',
    photo:'moons/rhea.png', credit:'NASA/JPL-Caltech/Space Science Institute.',
    desc:'Saturn\u2019s second largest moon \u2014 an ancient, heavily cratered iceball.',
    facts:[['Radius','763.5 km'],['Orbit period','4.518 d']] },
  { id:'titan', name:'Titan', system:'saturn', roman:'Saturn VI', disc:'moons/disc-titan.png', r:2574.8, period:15.945,
    blurb:'The only moon with a thick atmosphere \u2014 and methane lakes.',
    photo:'moons/titan-surface.png', credit:'The surface, photographed by the Huygens probe after it landed in January 2005. The rounded stones are water ice. ESA/NASA/JPL/University of Arizona.',
    desc:'The only moon with a thick atmosphere, and the only other world with standing liquid \u2014 methane lakes. Wider than Mercury, and the second largest moon in the solar system. In ordinary light the haze is opaque; Cassini\u2019s infrared spectrometer saw through it to bright equatorial dunes, darker highlands, and lakes near the pole.',
    facts:[['Radius','2,574.8 km'],['Orbit period','15.945 d'],['Atmosphere','Thick nitrogen\u2013methane haze'],['Landed','Huygens probe, January 2005']] },
  { id:'iapetus', name:'Iapetus', system:'saturn', roman:'Saturn VIII', disc:'moons/iapetus.png', r:734.3, period:79.333,
    blurb:'Two-toned: one hemisphere coal-dark, the other snow-bright.',
    photo:'moons/iapetus.png', credit:'The two hemispheres side by side. The ridge along the equator runs through both. NASA/JPL-Caltech/Space Science Institute.',
    desc:'One hemisphere is as dark as coal, the other as bright as snow. The dark side always leads, sweeping up material as it goes; ice sublimates away from the warmed surface and refreezes on the cold bright side. A ridge twenty kilometres high runs most of the way around the equator. Nobody knows why it is there.',
    facts:[['Radius','734.5 km'],['Orbit','3,560,820 km, 79.33 d']] },
  { id:'miranda', name:'Miranda', system:'uranus', roman:'Uranus V', disc:'moons/miranda.png', r:235.8, period:1.413,
    blurb:'Cliffs up to 20 km high \u2014 the tallest known anywhere.',
    photo:'moons/miranda.png', credit:'Voyager 2. NASA/JPL/USGS.',
    desc:'A pale battered globe scored by enormous grooved terraces, with cliffs up to 20 km high \u2014 the tallest known anywhere.',
    facts:[['Radius','235.8 km'],['Orbit period','1.413 d']] },
  { id:'ariel', name:'Ariel', system:'uranus', roman:'Uranus I', disc:'moons/ariel.png', discPos:'38% 48%', r:578.9, period:2.520,
    blurb:'The brightest Uranian moon, resurfaced by past tectonics.',
    photo:'moons/ariel.png', credit:'Voyager 2. NASA/JPL/USGS.',
    desc:'The brightest of Uranus\u2019s moons, cut by long branching rift valleys \u2014 evidence of past tectonic resurfacing.',
    facts:[['Radius','578.9 km'],['Orbit period','2.520 d']] },
  { id:'umbriel', name:'Umbriel', system:'uranus', roman:'Uranus II', disc:'moons/umbriel.png', discPos:'40% 48%', r:584.7, period:4.144,
    blurb:'The darkest of the five, with one puzzlingly bright ring.',
    photo:'moons/umbriel.png', credit:'Voyager 2. NASA/JPL/USGS.',
    desc:'The darkest of Uranus\u2019s moons, with one puzzlingly bright ring-shaped feature near its pole.',
    facts:[['Radius','584.7 km'],['Orbit period','4.144 d']] },
  { id:'titania', name:'Titania', system:'uranus', roman:'Uranus III', disc:'moons/titania.png', discPos:'38% 50%', r:788.9, period:8.706,
    blurb:'Largest Uranian moon, cut by enormous rift valleys.',
    photo:'moons/titania.png', credit:'Voyager 2. NASA/JPL/USGS.',
    desc:'The largest Uranian moon, cut by enormous rift valleys, with a long scarp running down its terminator.',
    facts:[['Radius','788.9 km'],['Orbit period','8.706 d']] },
  { id:'oberon', name:'Oberon', system:'uranus', roman:'Uranus IV', disc:'moons/oberon.png', r:761.4, period:13.463,
    blurb:'The outermost large Uranian moon, its craters filled dark.',
    photo:'moons/oberon.png', credit:'Voyager 2. NASA/JPL/USGS.',
    desc:'The outermost large Uranian moon, its crater floors filled with dark material.',
    facts:[['Radius','761.4 km'],['Orbit period','13.463 d']] },
  { id:'triton', name:'Triton', system:'neptune', roman:'Neptune I', disc:'moons/triton.png', r:1352.6, period:5.877,
    blurb:'Orbits backwards \u2014 a captured Kuiper-belt object.',
    photo:'moons/triton.png', credit:'Voyager 2, 1989. NASA/JPL/USGS.',
    desc:'Orbits backwards at 129\u00b0 inclination \u2014 a captured Kuiper-belt object with nitrogen geysers, a dimpled cantaloupe cap of nitrogen ice, and the coldest measured surface in the solar system.',
    facts:[['Radius','1,352.6 km'],['Orbit period','5.877 d, retrograde'],['Inclination','129\u00b0 \u2014 backwards']] },
  { id:'proteus', name:'Proteus', system:'neptune', roman:'Neptune VIII', disc:'moons/proteus.png', discPos:'44% 50%', r:208.0, period:1.122,
    blurb:'As large as a body can get without gravity pulling it round.',
    photo:'moons/proteus.png', credit:'Voyager 2. NASA/JPL/USGS.',
    desc:'About as large as a body can get without gravity pulling it round \u2014 a lumpy grey world found by Voyager 2.',
    facts:[['Radius','208.0 km'],['Orbit period','1.122 d']] },
  { id:'nereid', name:'Nereid', system:'neptune', roman:'Neptune II', disc:'moons/nereid.png', r:170.0, period:360.068,
    blurb:'One of the most eccentric orbits of any moon.',
    photo:'moons/nereid.png', credit:'Voyager 2 resolved only a few dozen pixels \u2014 shown enlarged. NASA/JPL/USGS.',
    desc:'One of the most eccentric orbits of any moon: it swings between 1.4 and 9.7 million kilometres from Neptune on a 360-day loop. Voyager 2 passed too far off to resolve more than a smudge.',
    facts:[['Radius','170.0 km'],['Orbit','1.4\u20139.7 million km, 360.07 d']] }
];

// True-relative-size line-up (the seven largest moons, and Mercury for scale)
export const SCALE_SET = [
  { name:'Ganymede', km:2631, img:'moons/gp-ganymede.png', moon:true },
  { name:'Titan', km:2575, img:'moons/disc-titan.png', moon:true },
  { name:'Mercury', km:2440, img:'moons/disc-mercury.png', moon:false },
  { name:'Callisto', km:2410, img:'moons/disc-callisto.png', moon:true },
  { name:'Io', km:1822, img:'moons/gp-io.png', moon:true },
  { name:'The Moon', km:1737, img:'moons/moon.png', moon:true },
  { name:'Europa', km:1561, img:'moons/gp-europa.png', moon:true },
  { name:'Triton', km:1353, img:'moons/triton.png', moon:true }
];

export const FRAMES = [
  { id:'a', src:'images/01-turbulent-south.png', title:'Turbulent South', region:'South', treatment:'Enhanced colour', dims:'960 \u00d7 1495',
    note:'A tall crop running from the temperate bands down toward the pole. The pale ovals strung along the upper bands are long-lived anticyclones; between and below them the cloud deck breaks into folded filamentary regions, the crumpled grey-blue ribbons that mark where the zonal flow loses its grip.' },
  { id:'b', src:'images/02-south-polar.png', title:'South Polar Approach', region:'Polar', treatment:'Enhanced colour', dims:'960 \u00d7 540',
    note:'Looking across the terminator toward the southern polar region. Colour has been pushed to separate the dusty green haze of the polar cap from the warmer banded latitudes above it. The dark ovals scattered across the lower half are cyclonic.' },
  { id:'c', src:'images/03-southern-ovals.png', title:'Southern Ovals', region:'South', treatment:'Enhanced colour', dims:'960 \u00d7 720',
    note:'A near-full southern hemisphere with the limb held intact. Several white ovals and one ringed grey-green vortex sit along the same latitude, which is how these storms usually behave: they queue up in a band and stay there for years.' },
  { id:'d', src:'images/04-limb-terminator.png', title:'Limb and Terminator', region:'Limb', treatment:'Enhanced colour', dims:'960 \u00d7 607',
    note:'The frame is dominated by the curve of the planet against black, with the terminator cutting across the bottom. Rust-coloured belts run down the left; the right side dissolves into a field of small vortices near the pole.' },
  { id:'e', src:'images/05-golden-filaments.png', title:'Golden Filaments', region:'South', treatment:'High contrast', dims:'960 \u00d7 604',
    note:'Contrast pushed hard and colour pulled warm. The treatment sacrifices anything like natural colour in exchange for structure: every fold, curl and shear line in the filamentary regions is legible, and the white ovals read as discs rather than smudges.' },
  { id:'f', src:'images/06-blue-north.png', title:'Blue North over Ovals', region:'North', treatment:'High contrast', dims:'960 \u00d7 1706',
    note:'The tallest crop in the set, and the sharpest contrast between hemispheric character: a cold blue polar region, granular with small cyclones, giving way to warm ochre bands studded with bright ovals along the lower limb.' },
  { id:'g', src:'images/07-low-light.png', title:'Low Light Vortices', region:'South', treatment:'Low light', dims:'960 \u00d7 678',
    note:'A dim frame worked up from very little signal. The gold filaments against near-black cloud show what aggressive stretching can recover, and also what it costs \u2014 the noise floor is visible, and the shadowed limb has gone flat.' },
  { id:'h', src:'images/08-banded-hemisphere.png', title:'Banded Hemisphere', region:'North', treatment:'Enhanced colour', dims:'960 \u00d7 539',
    note:'A wide view with the bands running left to right and dozens of vortices packed into the shear zones between them. This is closer to a survey frame than a portrait: the interest is in the density of features, not any one of them.' },
  { id:'i', src:'images/09-north-dome.png', title:'Northern Dome', region:'North', treatment:'Enhanced colour', dims:'960 \u00d7 539',
    note:'The planet held as a dome against black, warm at the limb and cooling toward the lower edge. Dozens of small vortices are packed into the shear zones; a handful of bright ovals sit on the upper bands.' },
  { id:'j', src:'images/10-blue-vortex-field.png', title:'The Blue Field', region:'North', treatment:'Enhanced colour', dims:'960 \u00d7 540',
    note:'Colour pushed until the deep cloud reads as ocean blue and every cyclone stands out white against it. This is enhancement as authorship: the structure is real, the palette is a decision.' },
  { id:'k', src:'images/11-pale-dome-oval.png', title:'Pale Dome', region:'North', treatment:'Natural colour', dims:'960 \u00d7 539',
    note:'A restrained treatment of much the same geometry \u2014 cream and dust rather than blue. One bright oval sits near the centre with a wake of small curls trailing behind it.' },
  { id:'l', src:'images/12-jonsson-bright.png', title:'Cyclone, Lifted', region:'Close-up', treatment:'Enhanced colour', dims:'960 \u00d7 1469', credit:'Bj\u00f6rn J\u00f3nsson',
    note:'The same frame as Cyclone, As Received, brightened and stretched until the cloud structure is fully legible. The blue speckle at the top left is noise the stretch has amplified along with everything else.' },
  { id:'m', src:'images/13-jonsson-dark.png', title:'Cyclone, As Received', region:'Close-up', treatment:'Low light', dims:'960 \u00d7 1469', credit:'Bj\u00f6rn J\u00f3nsson',
    note:'The unbrightened version of the frame beside it. Almost everything in the lifted version is present here \u2014 it is simply too dark to see, which is the whole argument for processing in one picture.' },
  { id:'n', src:'images/14-crescent-north.png', title:'Northern Crescent', region:'Limb', treatment:'Enhanced colour', dims:'960 \u00d7 960',
    note:'A crescent cut hard against black by the terminator. The teal fringe along the straight edge is a mosaicking artifact where the strips were joined and not cropped away.' },
  { id:'o', src:'images/15-vortex-grain.png', title:'Vortex, Grain and All', region:'Close-up', treatment:'High contrast', dims:'960 \u00d7 962',
    note:'A single storm at maximum stretch. Sharpening has raised the noise into visible grain and pushed the colour toward mauve and bronze \u2014 legibility bought at the cost of everything else.' },
  { id:'p', src:'images/16-merging-storms.png', title:'Merging Storms', region:'Close-up', treatment:'High contrast', dims:'960 \u00d7 960',
    note:'Two bright cores folded into one another inside a larger circulation. The same aggressive treatment as its neighbour, and the same trade: every filament visible, no colour you could call true.' },
  { id:'q', src:'images/17-tall-crescent-a.png', title:'Terminator Crescent I', region:'Limb', treatment:'Enhanced colour', dims:'960 \u00d7 2880',
    note:'An extremely tall crop keeping the full curve of the lit limb. A single bright oval anchors the middle of the frame; the rest dissolves into blue shadow toward the terminator.' },
  { id:'r', src:'images/18-tall-crescent-b.png', title:'Terminator Crescent II', region:'Limb', treatment:'Enhanced colour', dims:'960 \u00d7 2880',
    note:'A second pass at the same geometry, warmer and dustier. Placed beside the first it shows how far two colour balances can drift while describing identical cloud.' },
  { id:'s', src:'images/19-vortex-soft.png', title:'Vortex, Restrained', region:'Close-up', treatment:'Natural colour', dims:'960 \u00d7 960',
    note:'The quiet treatment of a close-up storm: soft blue-grey, minimal sharpening, noise left where it fell. Less to look at, and much closer to what the detector actually reported.' },
  { id:'t', src:'images/20-orange-band-dome.png', title:'Orange Band', region:'North', treatment:'Enhanced colour', dims:'960 \u00d7 540',
    note:'A rust-coloured belt runs along the top of the dome, with a bright zone beneath it and a scattering of white ovals below that. A conventional Jupiter, competently rendered.' },
  { id:'u', src:'images/21-grs-crescent.png', title:'Red Spot on the Crescent', region:'Red Spot', treatment:'Natural colour', dims:'960 \u00d7 914',
    note:'The Great Red Spot near the upper limb of a crescent, small in the frame and unmistakable. The colour here is held close to plausible, which makes the spot read orange rather than red.' },
  { id:'v', src:'images/22-pale-oval-closeup.png', title:'Pale Oval', region:'Close-up', treatment:'Natural colour', dims:'960 \u00d7 744',
    note:'A single anticyclone filling most of the frame, pale green-white against olive cloud. The near-monochrome result is what happens when a processor declines to push saturation at all.' },
  { id:'w', src:'images/23-banded-orange.png', title:'Banded, Orange to Blue', region:'North', treatment:'Enhanced colour', dims:'960 \u00d7 466',
    note:'A wide letterbox crop through several belts at once, running from a deep orange band on the left to blue-grey turbulence on the right. Good for showing how abruptly the zonal character changes.' },
  { id:'x', src:'images/24-io-wide.png', title:'Io Below the Bands', region:'Moons', treatment:'Low light', dims:'960 \u00d7 768',
    note:'Io as a small mottled disc against the shadowed lower limb of Jupiter. The violet cast comes from lifting a very dark exposure far enough to see the moon at all.' },
  { id:'y', src:'images/25-io-tall.png', title:'Io at the Limb', region:'Moons', treatment:'Low light', dims:'960 \u00d7 1200',
    note:'The same encounter framed vertically, with Io just clear of the planet\u2019s edge. Almost the whole frame is black; the composition is doing more work than the processing.' },
  { id:'z', src:'images/26-brown-barges.png', title:'Brown Barges', region:'North', treatment:'Enhanced colour', dims:'960 \u00d7 540',
    note:'Two dark brown belts run diagonally across the frame, broken by the elongated cyclonic features long known as barges. The blue-white zone between them is the sharpest boundary in the set.' },
  { id:'aa', src:'images/27-full-disc.png', title:'Most of a Planet', region:'Limb', treatment:'Natural colour', dims:'960 \u00d7 1200', credit:'Rachel Richards',
    note:'A nearly complete disc, lit from the left and falling into shadow at the lower right. Restrained colour and a lot of empty black \u2014 a portrait rather than a survey.' },
  { id:'ab', src:'images/28-jupiter-with-io.png', title:'Jupiter and Io, from Far Off', region:'Moons', treatment:'Natural colour', dims:'960 \u00d7 677',
    note:'A distant full-disc view with Io well clear of the planet \u2014 a very different vantage from the close perijove passes that produced everything else here, and worth including for exactly that reason.' },
  { id:'ac', src:'images/29-grs-square.png', title:'The Great Red Spot', region:'Red Spot', treatment:'Enhanced colour', dims:'960 \u00d7 960',
    note:'The spot at the top of the frame with the turbulent wake trailing away beneath it. The chains of small white curls below are where the storm shears the flow it sits in.' },
  { id:'ad', src:'images/30-grs-wide.png', title:'Red Spot at the Edge', region:'Red Spot', treatment:'Enhanced colour', dims:'960 \u00d7 540',
    note:'The spot pushed to the left edge and rendered a deep brick red, with the rest of the frame given over to the banded flow downstream of it.' }
];

export const REGIONS = ['All','North','South','Polar','Limb','Close-up','Red Spot','Moons'];
export const TREATMENTS = ['All','Natural colour','Enhanced colour','High contrast','Low light'];

export const STORY = {
  kicker:'Raw frames, public hands',
  title:'Jupiter, developed by strangers',
  lede:'JunoCam was carried to Jupiter as an outreach instrument. The mission posts the raw frames and invites anyone to download them, process them, and upload the result. Almost every Jupiter picture you have seen from this spacecraft passed through someone\u2019s afternoon.',
  stats:[['9h 56m','One Jupiter day \u2014 the fastest rotation in the solar system'],['318\u00d7','Earth\u2019s mass, and more than twice that of every other planet combined'],['1.3\u00d7','Earth\u2019s width \u2014 the Great Red Spot today, down from twice that in 1979'],['320 km','How far the Red Spot\u2019s roots reach below the cloud tops']],
  sections:[
    ['A camera that cannot hold still','JunoCam is a pushframe imager. Its filter strips are bonded directly onto the detector \u2014 1600 pixels wide, about 155 rows high \u2014 and the spacecraft\u2019s own rotation scans them across the planet. At the nominal two revolutions per minute, a frame lands roughly every 400 milliseconds.'],
    ['Four filters and a trick','Three visible strips \u2014 red, green, blue \u2014 plus a narrowband methane filter near 890 nanometres. The spin would smear anything exposed longer than 3.2 milliseconds, so the camera shifts the image down one row every 3.2 milliseconds to cancel the motion, up to about a hundred steps.'],
    ['Eight bits, and fading','Pixels leave the detector 12 bits deep and are companded to 8 bits inside the instrument; that is the form the public gets. Jupiter\u2019s radiation belts are steadily degrading the camera \u2014 later perijoves show reduced dynamic range and more noise, which is now part of the processing problem.'],
    ['What counts as processing','The invitation is deliberately loose. Cropping counts. So does pulling one atmospheric feature out of the murk, pushing colour past what the eye would see, stitching frames into collages, or reconstructing colour from the separate filter strips. The only hard rules are about logos and decency.'],
    ['Why the pictures keep changing','No two people develop the same frame the same way. Colour balance, stretch, sharpening and geometry are all judgement calls, and the raw 8-bit data leaves plenty of room for them. Compare any two versions of the same perijove and the disagreement is the point.']
  ]
};

export const SOURCES = [
  ['Physical data','NASA Planetary Fact Sheets, nssdc.gsfc.nasa.gov'],
  ['Spin and pole','IAU WGCCRE 2015 \u2014 Archinal et al. 2018'],
  ['Satellite data','The Sol orrery\u2019s satellite table \u2014 radius, orbit, period, eccentricity, density for 21 moons'],
  ['Jupiter frames','NASA/JPL-Caltech/SwRI/MSSS, processed by JunoCam citizen scientists \u2014 Mission Juno processing gallery'],
  ['Photographs','Cassini, Voyager 1 & 2, Galileo, Juno, MESSENGER, Magellan, DSCOVR, SDO, Huygens \u2014 NASA/JPL-Caltech and partner institutions'],
  ['Surface maps','Solar System Scope (CC-BY 4.0), composited from NASA source data']
];
